In [ ]:
import numpy as np

# Input data with shape (1, 28, 28)
input_data = np.random.rand(1, 28, 28)

# 3x3 filter
filter_data = np.random.rand(3, 3)

# Zero padding of size 1 on each side
padding = ((1 - 1) * 1) + 3 - 28 = 1
padded_input = np.pad(input_data, ((0,0), (1,1), (1,1)), 'constant')

# Output with shape (1, 28, 28)
output = np.zeros((1, 28, 28))

# Loop over the padded input data and apply the filter
for i in range(28):
    for j in range(28):
        output[:, i, j] = np.sum(padded_input[:, i:i+3, j:j+3] * filter_data)

print(output)

In [3]:
import tensorflow as tf
import numpy as np


# Input data with shape (1, 28, 28, 1)
input_data = tf.keras.layers.Input(shape=(28, 28, 1))

# 3x3 filter
x = tf.keras.layers.Conv2D(filters=1, kernel_size=(3, 3), strides=1, padding='same')(input_data)

# Create the model
model = tf.keras.models.Model(inputs=input_data, outputs=x)

# Generate some random input data
input_data = np.random.rand(1, 28, 28, 1)

# Apply the model to the input data
output = model(input_data)

print(output)

tf.Tensor(
[[[[-0.03914277]
   [ 0.41738427]
   [-0.2560535 ]
   [ 0.3976615 ]
   [-0.03773469]
   [-0.06918304]
   [ 0.42550233]
   [ 0.24899161]
   [-0.31471044]
   [ 0.36763608]
   [ 0.32135677]
   [ 0.07345577]
   [ 0.19005513]
   [ 0.01457331]
   [ 0.08566482]
   [ 0.29806545]
   [ 0.15736265]
   [-0.17295754]
   [ 0.3867861 ]
   [ 0.0821083 ]
   [ 0.25946188]
   [ 0.16913567]
   [ 0.3576791 ]
   [-0.38554633]
   [ 0.7258772 ]
   [-0.09347209]
   [ 0.03832623]
   [ 0.3364128 ]]

  [[ 0.27080742]
   [ 0.19084571]
   [ 0.46958613]
   [ 0.03988802]
   [ 0.49244305]
   [ 0.08812995]
   [-0.01974318]
   [ 0.3312459 ]
   [ 0.400114  ]
   [ 0.03334555]
   [ 0.38469133]
   [ 0.32766506]
   [ 0.4269948 ]
   [-0.03023451]
   [ 0.07943234]
   [ 0.26705334]
   [ 0.04310165]
   [ 0.41980088]
   [-0.03158727]
   [ 0.4327972 ]
   [ 0.81504905]
   [ 0.17145427]
   [-0.0976059 ]
   [ 0.177395  ]
   [ 0.41198155]
   [ 0.872189  ]
   [ 0.16538751]
   [ 0.29750255]]

  [[ 0.24775125]
   [ 0.0454464 ]

# An example of how to use 'valid' padding`

In [ ]:
# Input data with shape (1, 28, 28, 1)
input_data = tf.keras.layers.Input(shape=(28, 28, 1))

# 3x3 filter with valid padding
x = tf.keras.layers.Conv2D(filters=1, kernel_size=(3, 3), strides=1, padding='valid')(input_data)

# New Section# An example of how to use 'same' padding`

In [ ]:
# Input data with shape (1, 28, 28, 1)
input_data = tf.keras.layers.Input(shape=(28, 28, 1))

# 3x3 filter with same padding
x = tf.keras.layers.Conv2D(filters=1, kernel_size=(3, 3), strides=1, padding='same')(input_data)